name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.config.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows VS2017, os: windows-2016   }
        - { name: Windows VS2019, os: windows-latest }
        - { name: Linux GCC,      os: ubuntu-latest  }
        - { name: Linux Clang,    os: ubuntu-latest, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
        - { name: MacOS XCode,    os: macos-latest,  flags: -DSFML_BUILD_FRAMEWORKS=FALSE, prefix: sudo }
    steps:
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev

    - name: Checkout CSFML
      uses: actions/checkout@v2
      with:
        repository: CSFML/CSFML
        ref: 2.5.1
        path: CSFML

    - name: Configure CSFML CMake
      shell: bash
      run: cmake -S $GITHUB_WORKSPACE/CSFML -B $GITHUB_WORKSPACE/CSFML/build -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/CSFML/install -DBUILD_SHARED_LIBS=TRUE -DSFML_BUILD_EXAMPLES=FALSE -DSFML_BUILD_TEST_SUITE=FALSE -DCMAKE_VERBOSE_MAKEFILE=ON ${{matrix.platform.flags}}
    
    - name: Build CSFML
      shell: bash
      run: ${{matrix.platform.prefix}} cmake --build $GITHUB_WORKSPACE/CSFML/build --config Release --target install

    - name: Checkout CSFML
      uses: actions/checkout@v2
      with:
        path: CSFML

    - name: Configure CSFML CMake
      shell: bash
      run: cmake -S $GITHUB_WORKSPACE/CSFML -B $GITHUB_WORKSPACE/CSFML/build -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/CSFML/install -DBUILD_SHARED_LIBS=TRUE -DCSFML_LINK_SFML_STATICALLY=FALSE -DSFML_DIR=$GITHUB_WORKSPACE/CSFML/install/lib/cmake/CSFML -DCMAKE_VERBOSE_MAKEFILE=ON ${{matrix.platform.flags}}

    - name: Build CSFML
      shell: bash
      run: cmake --build $GITHUB_WORKSPACE/CSFML/build --config Release --target install
